### ISSUE TITLE
http 404 not found when click the button "quick chart"

### ISSUE THREAD

**Issue by RuizheIsaf** [jeonghanlee/epicsarchiverap-env#17]
hi @jeonghanlee ,
      As the figure show, "404 not found" occur when i clicked the button "quick chart" in order to show the history data of a PV, i think perhaps that i don't have the software "archViewer"? or some problems of Tomcat? I'm not sure if this is a problem with the environment configuration, but my other features work well, could you help me to check the problem.
      looking forward to your reply and thanks a lot
Ruizhe
![AA_question](https://user-images.githubusercontent.com/92136250/142217786-00266501-e824-4edc-8543-7f1b3abc5f93.jpeg)
e

**Comment by jeonghanlee** [comment]
@RuizheIsaf please check your appliances.xml. My recommendation is to use 192.168.20.128 instead of any hostname, and localhost.

**Comment by RuizheIsaf** [comment]
Thanks a lot for your recommendation @jeonghanlee,
I think this is the problem of network configuration, because everything work well when i install AA in my own MacBook VMware Fusion. The figures show the configuration of appliances.xml and archappl.conf, i think they are correct...
what's more, i really don't understand how epics AA distribute PV to each appliance of a cluster(which has 3 ~ 5 appliances), according to RAM or CPU capacity...? If an appliance crash, the PVs which are archived in this appliance will be moved to other appliances automatically?
Thanks again for your help!
Ruizhe
![AA1](https://user-images.githubusercontent.com/92136250/142425914-c1408f75-91cb-4028-a5ae-46e08320ac97.jpeg)
![AA2](https://user-images.githubusercontent.com/92136250/142426067-d972199a-845f-4530-9f40-e407c8d9fa54.jpeg)

**Comment by jeonghanlee** [comment]
@RuizheIsaf Unfortunately, the current repository doesn't support the multiple appliances configuration. Technically, you can use the repo to install numerous instances, but for all configurations, you have to modify all configurations according to your setup for all configurations. 

Please check the appliances.xml file defined in the following guide http://slacmshankar.github.io/epicsarchiver_docs/installguide.html

And compare it with you. You may see what the difference is.

It would be best if you study how they work first to understand how archiver appliance works. And it would be best if you test what kind of situation you will see according to your situation. I cannot guarantee my explanation is valid for your configuration.

**Comment by jeonghanlee** [comment]
The user jumped to new issue at the epicsarchiverap with the same question. I left a more detailed answer to this question. 

https://github.com/slacmshankar/epicsarchiverap/issues/129#issuecomment-973857558

This issue is invalid because we don't support multiple archiver appliance instances within this repository.
