### ISSUE TITLE
I/O error of Tomcat...

### ISSUE THREAD

**Issue by RuizheIsaf** [jeonghanlee/epicsarchiverap-env#18]
hi, @jeonghanlee 
I met a question about tomcat9, my appliance can work for hours, but it seems not stable...when i restart the epicsAA service, it tell s me that "I/O error" of tomcat as the figure shows. I think perhaps that i archived too many waveform PVs and data flow is too large leading to this problem?
could you give me some recommendation. thanks a lot.
Ruizhe
![AAA](https://user-images.githubusercontent.com/92136250/143984151-dee2ee4d-bc66-4d78-9454-d433903c42b3.jpeg)

**Comment by jeonghanlee** [comment]
Line 516 told 

```
515   if [ ! -z "$CATALINA_PID" ]; then
516     echo $! > "$CATALINA_PID"
517   fi
```

It could be permission, your disk link error, disk corruption, or anything. 

My other suggestion: please install everything with a user with sudo permission, not root account. 

When you run it as root, it may be a possible issue on bash scripts.

**Comment by jeonghanlee** [comment]
https://github.com/slacmshankar/epicsarchiverap/issues/131

**Comment by RuizheIsaf** [comment]
@jeonghanlee hi,
yes, it is the problem of disk, because i run epics AA at vmware exsi, the partition of disk is not same as that in real environment...
thanks for your help~
ruizhe
