### ISSUE TITLE
build error on Debian 11

### ISSUE THREAD

**Issue by filipleemans** [jeonghanlee/epicsarchiverap-env#19]
Dear @jeonghanlee, 

On a debian 11 variant during the "make build", I receive the following errors:
`...
[javadoc] error: An internal exception has occurred. 
  [javadoc]   	(java.lang.RuntimeException: java.io.FileNotFoundException: docs/api/mgmtpathmappings.txt (No such file or directory))
...
`
Do you have any idea what can be the cause?

Thank you in advance,
Filip

**Comment by jeonghanlee** [comment]
@filipleemans, please test the latest commit. So far, I have ignored the Javadoc build, which technically has no dependence upon the running archiver appliance.

**Comment by jeonghanlee** [comment]
@filipleemans, I think the issue was resolved. If not, please let me know.

**Comment by filipleemans** [comment]
Indeed @jeonghanlee . Thank you. I could trace the problem back to a memory issue.
