### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by rushiraval0** [jeonghanlee/epicsarchiverap-env#20]
Will this work on windows 10 platform?

**Comment by jeonghanlee** [comment]
This environment is based on bash and makefile. It may work if you have the proper and tight environment in Windows. But this repository doesn't work well with Windows. 

Do you have any specific reason to use Windows for the Archiver Appliance?

**Comment by jeonghanlee** [comment]
I closed it because this repo does not support the Windows platform.
