### ISSUE TITLE
Archived pvs not connected on reboot Debian 11

### ISSUE THREAD

**Issue by justinabraham** [jeonghanlee/epicsarchiverap-env#21]
Hi,

Thank you for the archiver config environment, it was straightforward to get an instance of the archiver running on a fresh install.

*OS: Debain 11 kernel 5.10.162-1 (2023-01-21) x86_64 GNU/Linux*
*Ver: EPICS Archiver Appliance Version d3dd9cc-2022-08-08-als_SNAPSHOT_03-February-2023T12-03-32*

I was able to archive pvs, however when I restart the PC the archiver service runs but all pvs are in a disconnected state as shown below:

![pvs](https://user-images.githubusercontent.com/3592113/216908307-e64e46b8-cc79-4ee0-b092-f24db8bb8d58.JPG)

Running `sudo systemctl status epicsarchiverap.service` everything looks okay to me:

![startup](https://user-images.githubusercontent.com/3592113/216908851-e67cf279-85b5-45f5-9f8f-0bd9caaf77f2.JPG)

If I simply `sudo systemctl restart epicsarchiverap.service` - service restarts and all pvs are in a connected state.

Not sure if there is some configuration issue on my machine or any other suggestions I could look into.

**Comment by jeonghanlee** [comment]
@justinabraham There may be the systemd dependency issue. I will look at them when I am available later.
