### ISSUE TITLE
Support for Rocky Linux

### ISSUE THREAD

**Issue by CubicTec** [jeonghanlee/epicsarchiverap-env#8]
**Where I was stuck:**
When trying to install on Rocky Linux, and running 
`make install.pkgs`
Log shows that it stop by system check or something.

>[rocky@localhost epicsarchiverap-env]$ make install.pkgs
>[sudo] password for rocky: 
>
>Doesn't support the detected Rocky Linux 8.4 (Green Obsidian)
>Please contact jeonghan.lee@gmail.com

**The solution I  can think of**
Identify Rocky Linux as CentOS 8 to share the same instruction code.

**Comment by jeonghanlee** [comment]
Please try the latest one, I don't test it fully, since I don't have the running rocky8 machine yet. So let me know if you see other problems.

**Comment by CubicTec** [comment]
> Please try the latest one, I don't test it fully, since I don't have the running rocky8 machine yet. So let me know if you see other problems.

It works! Thank you!

BTW, since PowerTools is not included in Rocky Linux by default
could replace
 `dnf config-manager --enable PowerTools`
by
`sudo dnf -y install dnf-plugins-core`
`sudo install epel-release`
`sudo dnf config-manager --set-enabled powertools`

**Comment by jeonghanlee** [comment]
I removed that commands, CentOS8 changed their package name continuously, in the document file.  The commands are defined within `make install.pkgs`. Please see the following script, was called by that rule.

https://github.com/jeonghanlee/epicsarchiverap-env/blob/7f45cad241447e4d026c36417734982a088081c6/scripts/required_pkgs.sh#L88
